# -*- coding: utf-8 -*-
"""Actividad Mapper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r8IC28imXMWKzNdaNntRdcgLP5XR3zdD

# Librerias
"""

!pip install kmapper

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import kmapper as km
from sklearn.cluster import AgglomerativeClustering

"""# Base de datos"""

df = pd.read_csv("job_salary_prediction_dataset.csv")

df

df.info()

"""# Limpieza"""

TituloTrabajo = df['job_title'].unique()
AñosExp = df['experience_years'].unique()
NivelEducacion = df['education_level'].unique()
ConteoAbilidades = df['skills_count'].unique()
industria = df['industry'].unique()
tamañoCompañia = df['company_size'].unique()
local = df['location'].unique()
TrabajoRemoto = df['remote_work'].unique()
certififcaciones = df['certifications'].unique()
Salario = df['salary'].unique()

print("Valores de job_title: ",TituloTrabajo)
print("Valores de experience_years: ",AñosExp)
print("Valores de education_level: ",NivelEducacion)
print("Valores de skills_count: ",ConteoAbilidades)
print("Valores de industry: ",industria)
print("Valores de company_size: ",tamañoCompañia)
print("Valores de location: ",local)
print("Valores de remote_work: ",TrabajoRemoto)
print("Valores de certifications: ",certififcaciones)
print("Valores de salary: ",Salario)

df['job_title'], uniques = pd.factorize(df['job_title'])
df['education_level'], uniques = pd.factorize(df['education_level'])
df['industry'], uniques = pd.factorize(df['industry'])
df['company_size'], uniques = pd.factorize(df['company_size'])
df['location'], uniques = pd.factorize(df['location'])
df['remote_work'], uniques = pd.factorize(df['remote_work'])

TituloTrabajo = df['job_title'].unique()
AñosExp = df['experience_years'].unique()
NivelEducacion = df['education_level'].unique()
ConteoAbilidades = df['skills_count'].unique()
industria = df['industry'].unique()
tamañoCompañia = df['company_size'].unique()
local = df['location'].unique()
TrabajoRemoto = df['remote_work'].unique()
certififcaciones = df['certifications'].unique()
Salario = df['salary'].unique()

print("Valores de job_title: ",TituloTrabajo)
print("Valores de experience_years: ",AñosExp)
print("Valores de education_level: ",NivelEducacion)
print("Valores de skills_count: ",ConteoAbilidades)
print("Valores de industry: ",industria)
print("Valores de company_size: ",tamañoCompañia)
print("Valores de location: ",local)
print("Valores de remote_work: ",TrabajoRemoto)
print("Valores de certifications: ",certififcaciones)
print("Valores de salary: ",Salario)

"""# Grafo

## PCA
"""

# Variable objetivo
X = df.copy()
X.drop('salary', axis=1, inplace=True)

# Normalizar
X_scaled = StandardScaler().fit_transform(X)

# PCA
pca = PCA(n_components=1)
lens = pca.fit_transform(X_scaled)

lens[:5]

"""## Mapper

- Función filtro: PCA
- Parámetros del cubrimiento:
  - n_cubes = 10
  - perc_overlap = 0.4
- Algoritmo de clustering: Single Linkage
"""

# Inicializar mapper
mapper = km.KeplerMapper()

# PCA como lente
lens = mapper.fit_transform(X_scaled, projection=PCA(n_components=1))

# Single linkage
clusterer = AgglomerativeClustering(n_clusters=None,
                                    distance_threshold=1.5,
                                    linkage='single')

# Mapper
graph = mapper.map(lens,
                   X_scaled,
                   clusterer=clusterer,
                   cover=km.Cover(n_cubes=10, perc_overlap=0.4))

# Visualización
mapper.visualize(graph, path_html="mapper.html")

"""## Exportar como lista de nodos y aristas"""

# Nodos
nodos = pd.DataFrame({"Nodos":list(graph['nodes'].keys()),"Puntos":[len(i) for i in graph['nodes'].values()]})

# Aristas
aristas = []
for n, coneccion in graph['links'].items():
  for c in coneccion:
    aristas.append((n,c))

aristas = pd.DataFrame(aristas,columns=["Origen","Destino"])

# Exportar
nodos.to_csv("nodos.csv",index=False)
aristas.to_csv("aristas.csv",index=False)